services:
  db:
    image: mysql:8.0.35
    container_name: db-ti
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: users-db
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    networks:
      - users_ti

networks:
  users_ti:
    driver: "bridge"

